-- MySQL Script generated by MySQL Workbench
-- Sun Jan 23 20:43:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sweng_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sweng_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sweng_2` DEFAULT CHARACTER SET utf8 ;
USE `sweng_2` ;

-- -----------------------------------------------------
-- Table `sweng_2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_2`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` CHAR(32) NOT NULL COMMENT 'md5 Hash verwenden',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_2`.`todo_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_2`.`todo_lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_todo_lists_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_todo_lists_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sweng_2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_2`.`todos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_2`.`todos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(90) NULL,
  `duedate` DATETIME NULL,
  `priority` INT NULL,
  `active` TINYINT NULL,
  `todo_lists_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_todos_todo_lists_idx` (`todo_lists_id` ASC),
  CONSTRAINT `fk_todos_todo_lists`
    FOREIGN KEY (`todo_lists_id`)
    REFERENCES `sweng_2`.`todo_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_2`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_2`.`calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(90) NOT NULL,
  `date` DATE NOT NULL,
  `invitedusers` VARCHAR(90) NULL,
  `users_id` INT NOT NULL,
  `startTime` FLOAT NOT NULL,
  `endTime` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_calendar_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_calendar_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sweng_2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_2`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_2`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(90) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `company` VARCHAR(60) NULL,
  `phone` VARCHAR(20) NULL,
  `mail` VARCHAR(60) NULL,
  `address` VARCHAR(180) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_contacts_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `sweng_2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
