-- MySQL Script generated by MySQL Workbench
-- Sun Jan 23 20:39:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sweng_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sweng_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sweng_1` DEFAULT CHARACTER SET utf8 ;
USE `sweng_1` ;

-- -----------------------------------------------------
-- Table `sweng_1`.`todo_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_1`.`todo_lists` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_1`.`todos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_1`.`todos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(90) NULL,
  `duedate` DATETIME NULL,
  `priority` INT NULL,
  `active` TINYINT NULL,
  `todo_lists_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_todos_todo_lists_idx` (`todo_lists_id` ASC),
  CONSTRAINT `fk_todos_todo_lists`
    FOREIGN KEY (`todo_lists_id`)
    REFERENCES `sweng_1`.`todo_lists` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_1`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_1`.`calendar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(90) NOT NULL,
  `date` DATE NOT NULL,
  `invitedusers` VARCHAR(90) NULL,
  `startTime` FLOAT NOT NULL,
  `endTime` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sweng_1`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sweng_1`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(90) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `company` VARCHAR(60) NULL,
  `phone` VARCHAR(20) NULL,
  `mail` VARCHAR(60) NULL,
  `address` VARCHAR(180) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
